version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    command: >
      bash -c "
        /etc/confluent/docker/run &
        echo 'Aguardando Kafka iniciar...';
        while ! kafka-topics --bootstrap-server localhost:9092 --list; do sleep 1; done;
        kafka-topics --create --topic orders --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092;
        kafka-topics --create --topic inventory-events --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092;
        tail -f /dev/null
      "